[tool.poetry]
name = "pangram-sdk"
version = "0.1.8"
description = ""
authors = ["Max Spero <max@pangramlabs.com>"]
readme = "README.md"
packages = [
    { include = "pangram" }
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
sphinx = "^3.0"
sphinxcontrib-httpdomain = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
